export const Routes = {
    auth: 'auth',
    apps: 'apps',
    app: 'app',
    other: 'other',
    consumer: 'consumer',
    Signin: 'signin',
    SignOut: 'signout',
    SignUp: 'signup',
    ResetPassword: 'reset-password',
    SetPassword: 'set-password',
    ForgetPassword: 'forget-password',
    Dashboard: 'apps/dashboard',
    _404: '404',
    _500: '500',
    _401: '401',
    Maintenance: 'maintenance',
    ComingSoon: 'coming-soon',
    consents: 'apps/consents',

    BusinessUnit: 'apps/business-unit',
    user: 'users',
    userRole: 'apps/users/roles',
    SystemConfig: 'system',
    accounts: 'accounts',
    products: 'products',
    userGroup: 'userGroups',
    beacons: 'beacons',
    ConsumerDashboard: 'dashboard',
    ConsumerDashboardConsents: 'dashboard/consents',
    ConsumerRequest: 'request',
    ConsumerAccess: 'access',
    ConsumerConfirm: 'confirm',
};
